# Generated by Django 5.0.1 on 2024-02-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
