# Generated by Django 5.0.1 on 2024-02-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_remove_activity_cost_remove_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.accommodation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='activity',
            field=models.ManyToManyField(null=True, to='travel_app.activity'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.transport'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='turists_places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.turistsplaces'),
        ),
    ]
