# Generated by Django 5.0.1 on 2024-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_destination_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turistsplaces',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
