# Generated by Django 5.0.1 on 2024-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_turistsplaces_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activity',
            field=models.ManyToManyField(to='travel_app.activity'),
        ),
    ]
