# Generated by Django 5.0.1 on 2024-02-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_alter_destination_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='address',
            new_name='accommodation_address',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='description',
            new_name='accommodation_description',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='name',
            new_name='accommodation_name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='description',
            new_name='destination_description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='destination_name',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='name',
            new_name='transport_name',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='description',
            new_name='transpost_description',
        ),
        migrations.RenameField(
            model_name='turistsplaces',
            old_name='description',
            new_name='turist_places_description',
        ),
    ]
