# Generated by Django 5.0.1 on 2024-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_rename_address_accommodation_accommodation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transpost_description',
            field=models.TextField(null=True),
        ),
    ]
