# Generated by Django 5.0.1 on 2024-02-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_alter_accommodation_accommodation_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='transpost_description',
            new_name='transport_description',
        ),
        migrations.RenameField(
            model_name='turistsplaces',
            old_name='turist_places_description',
            new_name='turists_places_description',
        ),
    ]
