# Generated by Django 5.0.1 on 2024-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_rename_transpost_description_transport_transport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_name',
            field=models.CharField(max_length=255),
        ),
    ]
