# Generated by Django 5.0.2 on 2024-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0010_alter_destination_destination_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='travel',
            field=models.ManyToManyField(to='travel_app.travel'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(),
        ),
    ]
