# Generated by Django 5.0.2 on 2024-02-08 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0012_remove_destination_travel_travel_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
