# Generated by Django 5.0.2 on 2024-02-08 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0013_alter_destination_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
